#!/usr/bin/python
#
# fuego-create-jobs - a tool to create a fuego jobs
#
# Copyright 2016 TOSHIBA Corporation
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of version 2 of the GNU General Public License as
#   published by the Free Software Foundation.  The GNU General Public
#   License is available online at: http://www.gnu.org/copyleft/gpl.html
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# Author: Daniel Sangorrin <daniel.sangorrin (at) toshiba.co.jp>
#
import subprocess
import sys

if __name__=="__main__":
    print("Deleting jobs")
    try:
        jobs = subprocess.check_output('java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080/fuego list-jobs', shell=True).splitlines()
        for job in jobs:
            subprocess.call('java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080/fuego delete-job ' + str(job), shell=True)
    except Exception as e:
        print(e)
        sys.exit(1)
