#!/usr/bin/python
#
# fuego-create-node - a tool to create a jenkins node
#
# Copyright 2016 TOSHIBA Corporation
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of version 2 of the GNU General Public License as
#   published by the Free Software Foundation.  The GNU General Public
#   License is available online at: http://www.gnu.org/copyleft/gpl.html
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# Author: Daniel Sangorrin <daniel.sangorrin (at) toshiba.co.jp>
#
import subprocess
import sys
import argparse

def create_node(board):
    tmp = "/tmp/fuego_tmp_node"
    fd = open(tmp, "w+")
    fd.write("""<?xml version='1.0' encoding='UTF-8'?>
<slave>
    <name>{board}</name>
    <description></description>
    <remoteFS>/tmp/dev-slave1</remoteFS>
    <numExecutors>1</numExecutors>
    <mode>NORMAL</mode>
    <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
    <launcher class="hudson.slaves.CommandLauncher">
    <agentCommand>java -jar /fuego-core/engine/slave.jar</agentCommand>
    </launcher>
    <label></label>
    <nodeProperties/>
</slave>
""".format(board=board))
    fd.close()

    print("Creating node " + board)
    try:
        subprocess.call('java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080/fuego create-node ' + board + ' < ' + tmp, shell=True)
        subprocess.call('rm -f ' + tmp, shell=True)
    except Exception as e:
        print("Node already exists")
        print(e)
        sys.exit(1)

if __name__=="__main__":
    parser = argparse.ArgumentParser(description='Create a jenkins node')
    parser.add_argument('-b', '--board', type=str, help='board name (e.g.: bbb for bbb.board)', required=True)
    args = parser.parse_args()
    create_node(args.board)
