#!/usr/bin/python
#
# fuego-delete-node - a tool to delete a jenkins node
#
# Copyright 2016 TOSHIBA Corporation
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of version 2 of the GNU General Public License as
#   published by the Free Software Foundation.  The GNU General Public
#   License is available online at: http://www.gnu.org/copyleft/gpl.html
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# Author: Daniel Sangorrin <daniel.sangorrin (at) toshiba.co.jp>
#
import subprocess
import sys
import argparse

def delete_node(board):
    print("Deleting node " + board)
    try:
        subprocess.call('java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080/fuego delete-node ' + board, shell=True)
    except Exception as e:
        print("Node didn't exist")
        print(e)
        sys.exit(1)

if __name__=="__main__":
    parser = argparse.ArgumentParser(description='Delete a jenkins node')
    parser.add_argument('-b', '--board', type=str, help='board name (e.g.: bbb for bbb.board)', required=True)
    args = parser.parse_args()
    delete_node(args.board)
